### ISSUE TITLE
There used to be ip protection. Where is she now?

### ISSUE THREAD

**Issue by CMAULTOP** [DiscordSRV/Documentation#63]
Previously, every time the plugin logged in, it checked the ip and if it changed, it asked the user to confirm the account using Discord by sending the code to the bot's private messages. Where is this feature now?

**Comment by ANutley** [comment]
Hey, DiscordSRV never has never checked whether players log in with the same IPs. In the future please ask questions like this on our [Discord server](https://discordsrv.com/discord) before opening an issue (especially on the Docs repo)
