### ISSUE TITLE
Spamming console with odd error

### ISSUE THREAD

**Issue by Gamer101233** [DiscordSRV/Documentation#65]
when someone joined the server i saw part of the cause of the spam with the follow error

Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 10008: Unknown Message

**Comment by granny** [comment]
Wrong repository and not detailed enough to be considered a bug report. If you need support, please [join our discord server](https://discordsrv.com/discord) and create a ticket through the #create-a-ticket channel.
