### ISSUE TITLE
Jda issue

### ISSUE THREAD

**Issue by BelgVolish** [DiscordSRV/Documentation#77]
When server starts, this error occures:

> [23:17:09 ERROR]: [DiscordSRV] An unknown error occurred building JDA...
> [23:17:09 ERROR]: [DiscordSRV] github.scarsz.discordsrv.dependencies.jda.api.exceptions.ErrorResponseException: 0: 500: Internal Server Error
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestAction.complete(RestAction.java:633)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.verifyToken(JDAImpl.java:373)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:300)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.login(JDAImpl.java:267)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.api.JDABuilder.build(JDABuilder.java:1874)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:893)
> [23:17:09 ERROR]: [DiscordSRV]  at java.base/java.lang.Thread.run(Thread.java:1583)
> [23:17:09 ERROR]: [DiscordSRV] Caused by: github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.api.exceptions.ContextException.here(ContextException.java:54)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.api.requests.Request.<init>(Request.java:71)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.api.requests.RestFuture.<init>(RestFuture.java:36)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209)
> [23:17:09 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.28.0 (1).jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219)
> [23:17:09 ERROR]: [DiscordSRV]  ... 7 more

**Comment by thewilloftheshadow** [comment]
Discord is currently having an outage, you can follow it here: https://discordstatus.com/incidents/wlf7gks7nb1m

**Comment by Dinty1** [comment]
This is also not the repository for the plugin itself.
